// Code generated by github.com/go-surreal/som, DO NOT EDIT.
package cbor

import (
	"github.com/fxamacker/cbor/v2"
)

var (
	// Cached encoding/decoding modes for optimal performance.
	// These are created once at package initialization and are
	// immutable and safe for concurrent use.
	defaultEncMode cbor.EncMode
	defaultDecMode cbor.DecMode

	// detEncMode uses RFC 8949 Core Deterministic Encoding so that
	// identical Go values always produce the exact same bytes.
	// Used for hashing/keying purposes (e.g. live query dedup).
	detEncMode cbor.EncMode
)

func init() {
	var err error

	// Create encoding mode with default options
	defaultEncMode, err = cbor.EncOptions{}.EncMode()
	if err != nil {
		panic("cbor: failed to create default EncMode: " + err.Error())
	}

	// Create decoding mode with default options
	defaultDecMode, err = cbor.DecOptions{}.DecMode()
	if err != nil {
		panic("cbor: failed to create default DecMode: " + err.Error())
	}

	// Create deterministic encoding mode (RFC 8949 Core Deterministic).
	// Map keys are sorted, producing canonical output for identical values.
	detEncMode, err = cbor.CoreDetEncOptions().EncMode()
	if err != nil {
		panic("cbor: failed to create deterministic EncMode: " + err.Error())
	}
}

// Marshal encodes v to CBOR format using a cached EncMode.
// This is faster than cbor.Marshal() for repeated operations
// due to mode reuse. It is safe for concurrent use.
func Marshal(v any) ([]byte, error) {
	return defaultEncMode.Marshal(v)
}

// Unmarshal decodes CBOR data into v using a cached DecMode.
// This is faster than cbor.Unmarshal() for repeated operations
// due to mode reuse. It is safe for concurrent use.
func Unmarshal(data []byte, v any) error {
	return defaultDecMode.Unmarshal(data, v)
}

// MarshalDet encodes v to CBOR using RFC 8949 Core Deterministic Encoding.
// Identical Go values always produce identical bytes, making the output
// suitable for hashing and equality comparisons.
func MarshalDet(v any) ([]byte, error) {
	return detEncMode.Marshal(v)
}

// Re-export commonly used types for convenience
type RawMessage = cbor.RawMessage
type RawTag = cbor.RawTag
type Tag = cbor.Tag
