// Code generated by github.com/go-surreal/som, DO NOT EDIT.
package cbor

import (
	"bytes"
	"fmt"
	"time"

	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// DateTime marshaling helpers
func MarshalDateTime(t time.Time) (RawMessage, error) {
	return Marshal(Tag{
		Number:  models.TagCustomDatetime,
		Content: []int64{t.Unix(), int64(t.Nanosecond())},
	})
}

func MarshalDateTimePtr(t *time.Time) (RawMessage, error) {
	if t == nil {
		return None(), nil
	}
	return MarshalDateTime(*t)
}

func UnmarshalDateTime(data []byte) (time.Time, error) {
	var val []int64
	if err := Unmarshal(data, &val); err != nil {
		return time.Time{}, err
	}
	if len(val) == 0 {
		return time.Time{}, nil
	}
	secs := val[0]
	nano := int64(0)
	if len(val) > 1 {
		nano = val[1]
	}
	return time.Unix(secs, nano).UTC(), nil
}

func UnmarshalDateTimePtr(data []byte) (*time.Time, error) {
	if IsNoneOrNull(data) {
		return nil, nil
	}
	t, err := UnmarshalDateTime(data)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Duration marshaling helpers
func MarshalDuration(d time.Duration) (RawMessage, error) {
	totalNanoseconds := d.Nanoseconds()
	totalSeconds := totalNanoseconds / int64(time.Second)
	remainingNanoseconds := totalNanoseconds % int64(time.Second)
	return Marshal(Tag{
		Number:  models.TagCustomDuration,
		Content: []int64{totalSeconds, remainingNanoseconds},
	})
}

func MarshalDurationPtr(d *time.Duration) (RawMessage, error) {
	if d == nil {
		return None(), nil
	}
	return MarshalDuration(*d)
}

func UnmarshalDuration(data []byte) (time.Duration, error) {
	var val []int64
	if err := Unmarshal(data, &val); err != nil {
		return 0, err
	}
	var dur time.Duration
	if len(val) > 0 {
		dur = time.Duration(val[0]) * time.Second
	}
	if len(val) > 1 {
		dur += time.Duration(val[1])
	}
	return dur, nil
}

func UnmarshalDurationPtr(data []byte) (*time.Duration, error) {
	if IsNoneOrNull(data) {
		return nil, nil
	}
	d, err := UnmarshalDuration(data)
	if err != nil {
		return nil, err
	}
	return &d, nil
}

// none is the canonical CBOR Tag 6 + null (0xc6 0xf6) encoding.
// SurrealDB uses CBOR Tag 6 to represent NONE, which is accepted by option<T> fields.
var none = [2]byte{0xc6, 0xf6}

// cborNull is the single-byte CBOR null encoding.
var cborNull = [1]byte{0xf6}

// None returns a fresh copy of the pre-encoded CBOR NONE bytes.
func None() RawMessage {
	b := none
	return b[:]
}

func IsNoneOrNull(data []byte) bool {
	return bytes.Equal(data, none[:]) || bytes.Equal(data, cborNull[:])
}

func RecordIDToString(id any) (string, error) {
	switch v := id.(type) {
	case string:
		return v, nil
	case Tag:
		if v.Number == models.TagSpecBinaryUUID {
			uuidBytes, ok := v.Content.([]byte)
			if !ok {
				return "", fmt.Errorf("expected []byte UUID content, got %T", v.Content)
			}
			if len(uuidBytes) != 16 {
				return "", fmt.Errorf("UUID must be 16 bytes, got %d", len(uuidBytes))
			}
			return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
				uuidBytes[0:4], uuidBytes[4:6], uuidBytes[6:8], uuidBytes[8:10], uuidBytes[10:16]), nil
		}
		return "", fmt.Errorf("unsupported CBOR tag %d in record ID (expected tag %d for UUID)", v.Number, models.TagSpecBinaryUUID)
	default:
		return "", fmt.Errorf("expected string or tagged ID, got %T", id)
	}
}

