site_name: SOM
site_url: https://go-surreal.github.io/som
docs_dir: content
theme:
  name: mkdocs
  custom_dir: theme

nav:
  - "Overview": overview.md
  - "Getting started":
    - "Introduction": getting-started/index.md
    - "Installation": getting-started/installation.md
    - "Concepts": getting-started/concepts.md
    - "Features": getting-started/features.md
  - "Usage":
      - "Overview": usage/index.md
      - "Generation": usage/generation.md
      - "Models": usage/models.md
      - "Data types": usage/data-types.md
      - "CRUD": usage/crud.md
      - "Queries": usage/queries.md
      - "Relations": usage/relations.md
  - "Development":
    - "Index": development/index.md
    - "Contribute": development/contribute.md
    - "Roadmap": development/roadmap.md
  - "Other":
    - "FAQ": other/faq.md
    - "About": other/about.md
